spring.application.name=FileTransferApplication
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

file.upload-dir=/home/amojaya/Documents/Programming/uploads
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB

# AWS S3 Configuration
aws.region=${AWS_REGION:us-east-1}
aws.bucket-name=${AWS_BUCKET_NAME:amzn-s3-file-store}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
