name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/file-transfer-app/File-Transfer-Application
            git pull origin main
            export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
            export PATH=$JAVA_HOME/bin:$PATH
            mvn clean package -DskipTests
            docker build -t file-transfer-application .
            sudo docker stop file-transfer-backend || true
            sudo docker rm file-transfer-backend || true
            sudo docker run -d \
              --restart=always \
              --name file-transfer-backend \
              -p 8080:8080 \
              --env-file /home/ec2-user/file-transfer-app/File-Transfer-Application/.env \
              file-transfer-application
            echo "Backend deployed successfully!"